
[font]
normal = { family = "FiraCode Nerd Font", style = "Retina"}
size = 16

[terminal.shell]
program = "tmux"

[window]
dimensions = { columns = 80, lines = 25}
opacity = 1

[env]
TERM = "xterm-256color"

[general]
import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]

