
[font]
normal = { family = "Maple Mono", style = "Regular"}
size = 16

[terminal.shell]
program = "tmux"

[window]
dimensions = { columns = 80, lines = 25}
opacity = 0.94


[env]
TERM = "xterm-256color"

[colors]
transparent_background_colors = true

[general]
import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   #"~/.config/alacritty/catppuccin-mocha.toml"
  #"~/.config/alacritty/tokyonight_storm"
]


