import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "FiraCodeNerdFont", style = "Regular"}
size = 16

[shell]
program = "/usr/bin/zsh"
args = ["--login"]

[window]
dimensions = { columns = 80, lines = 25}
opacity = 1

[env]
TERM = "xterm-256color"

